export enum ChatGatewayEventsEnum {
    PATH = '/socket/chat',
    SEND_MESSAGE = 'SEND_MESSAGE',
    REQUEST_MESSAGE = 'REQUEST_MESSAGE',
    RESPONSE_MESSAGE = 'RESPONSE_MESSAGE',
    RESPONSE_MESSAGE_IDENTIFIER = 'RESPONSE_MESSAGE_IDENTIFIER',
    REQUEST_JOIN_ROOM_IDENTIFIER = 'REQUEST_JOIN_ROOM_IDENTIFIER',



  }
  