export enum ConstructionProfessionalFunctionEnum {
    ARQUITETO = 'ARQUITETO',
    ENGENHEIRO = 'ENGINEER',
    TECNICO = 'TECNICO',
    MESTRE_DE_OBRA = 'MESTRE_DE_OBRA',
    PEDREIRO = 'PEDREIRO',
    PINTOR = 'PINTOR',
    ELETRICISTA = 'ELETRICISTA',
    ENCANADOR = 'ENCANADOR',
    GESSEIRO = 'GESSEIRO',
    MARCENEIRO = 'MARCENEIRO',
    VIDRACEIRO = 'VIDRACEIRO',
    OUTROS = 'OUTROS',
}
