export enum ConstructionType {
    AREA_REGULARIZADA = 'AREA_REGULARIZADA',
    AREA_PASSIVEL_DE_REGULARIZACAO = 'AREA_PASSIVEL_DE_REGULARIZACAO',
    PATRIMONIO_HISTORICO = 'PATRIMONIO_HISTORICO',
    PARQUE_IMOBILIARIO_DEGRADADO_DO_PODER_PUBLICO = 'PARQUE_IMOBILIARIO_DEGRADADO_DO_PODER_PUBLICO'
}