export enum ConstructionsStatusEnum {
  EM_ANDAMENTO = 'EM ANDAMENTO',
  EM_ANALISE = 'EM_ANALISE',
  CONCLUIDA = 'CONCLUIDA',
  CANCELADA = 'CANCELADA',
  REFAZER_FOTOS = 'REFAZER_FOTOS',
  FOTOS_EM_ANALISE = 'FOTOS_EM_ANALISE',
  FOTOS_CONCLUIDAS = 'FOTOS_CONCLUIDAS',
  FINALIZADA = 'FINALIZADA',
}
