export enum ContractResignedReasonEnum {
  FAILURE_TO_COMPLY_CLAUSES = "FAILURE_TO_COMPLY_CLAUSES",
  INCOMPATIBILITY_BETWEEN_THE_PARTIES = "INCOMPATIBILITY_BETWEEN_THE_PARTIES",
  UNFORESEEN_CIRCUMSTANCES = "UNFORESEEN_CIRCUMSTANCES",
  OTHERS = "OTHERS"
}