export enum ContractResignedStatusEnum {
  RESIGN_SOLICITATION = 'RESIGN_SOLICITATION',
  RESIGN_SCHEDULE = 'RESIGN_SCHEDULE',
  RESCHEDULE = 'RESCHEDULE',
  STATUS_REPORT = 'STATUS_REPORT',
  FEE_DISCHARGE = 'FEE_DISCHARGE',
  REALIZE_DISCHARGE = 'REALIZE_DISCHARGE',
  CONFIRM_DISCHARGE = 'CONFIRM_DISCHARGE',
  CONFIRM_RECEIVING = 'CONFIRM_RECEIVING',
  RESIGNED = 'RESIGNED'
}
