export enum ContractStatusEnum {
    INFORMACOES_PENDENTES = 'INFORMACOES_PENDENTES',
    RASCUNHO = 'RASCUNHO',
    INFOMACOES_ENVIADAS = 'INFOMACOES_ENVIADAS',
    AGUARDANDO_ASSINATURA = 'AGUARDANDO_ASSINATURA',
}