export enum ContractStatusEnum {
    PENDING='PENDING',
    REQUEST_CHANGE ='REQUEST_CHANGE',
    APPROVED ='APPROVED',
    REPROVED ='REPROVED',
    AWAITING_BENEFICIARY = 'AWAITING_BENEFICIARY',
    TO_SCHEDULE = 'TO_SCHEDULE',
    DELIVERY_SOLICITATION = 'DELIVERY_SOLICITATION',
    RESCHEDULE = 'RESCHEDULE',
    CONTRACT_DELIVERY = 'CONTRACT_DELIVERY',
    CONFIRM_DELIVERY = 'CONFIRM_DELIVERY',
    DELIVERED = 'DELIVERED',
    DRAFT = 'DRAFT',
}
