export enum CostEstimateStatusEnum {
    PENDING='PENDING',
    AWAITING_APPROVAL='AWAITING_APPROVAL',
    CHANGE_SOLICITATION ='CHANGE_SOLICITATION',
    REPROVED_ESTIMATION ='REPROVED_ESTIMATION',
    APPROVED_ESTIMATION ='APPROVED_ESTIMATION'
}