export enum DemandStatusEnum {
    RASCUNHO = "RASCUNHO",
    CADASTRADO_VISTORIA = "CADASTRADO_VISTORIA",
    ESPERANDO_MELHORIA = "ESPERANDO_MELHORIA",
    ESPERANDO_OBRA = "ESPERANDO_OBRA",
    CONCLUIR_OBRAS = "CONCLUIR_OBRAS",
    EM_ANALISE = "EM_ANALISE",
    CONCLUIDO = "CONCLUIDO",
    RESCISAO = "RESCISAO",
    CANCELADO = "CANCELADO",
}
