export enum ImprovementProjectStatusEnum {
    SEND_DOCUMENT = 'SEND_DOCUMENT',
    TO_SCHEDULE = 'TO_SCHEDULE',
    DELIVERY_SOLICITATION = 'DELIVERY_SOLICITATION',
    RESCHEDULE = 'RESCHEDULE',
    PROJECT_DELIVERY = 'PROJECT_DELIVERY',
    CONFIRM_DELIVERY = 'CONFIRM_DELIVERY',
    DELIVERED = 'DELIVERED',
    TERMINATION = 'TERMINATION'
}