export enum KinshipEnum {
  Me = "me",
  PaternalGrandmother = "paternalGrandmother",
  PaternalGrandfather = "paternalGrandfather",
  MaternalGrandmother = "maternalGrandmother",
  MaternalGrandfather = "maternalGrandfather",
  GrandChild = "grandChild",
  GrandDaughter = "grandDaugther",
  Nephew = "nephew",
  Niece = "niece",
  Mother = "mother",
  Father = "father",
  Son = "son",
  Daughter = "daughter",
  GreatGrandson = "greatGrandson",
  GreatGrandDaughter = "greatGrandDaughter",
  BrotherInLaw = "brotherInLaw",
  SisterInLaw = "sisterInLaw",
  Husband = "husband",
  Wife = "wife",
  Brother = "brother",
  Sister = "sister",
  Uncle = "uncle",
  Aunt = "aunt",
  Aggregate = "aggregate",
  Stepson = "stepson",
  Stepdaughter = "stepdaughter"
}