export enum TechnicalVisitTypeEnum {
    SOLICITACAO_DE_VISITA = 'SOLICITACAO_DE_VISITA',
    VISITA_TECNICA = 'VISITA_TECNICA',
    ESTIMATIVA_DE_CUSTO = 'ESTIMATIVA_DE_CUSTO',
    CONTRATO = 'CONTRATO',
    PROJETO_DE_MELHORIA = 'PROJETO_DE_MELHORIA',
    CADASTRO_DE_OBRA = 'CADASTRO_DE_OBRA',
    CONCLUSAO_DE_OBRA = 'CONCLUSAO_DE_OBRA',
    RECISAO_DE_CONTRATO = 'RECISAO_DE_CONTRATO'
}