export enum EnviromentVariablesEnum {
    PORT = 'PORT',
    ENABLE_CORS = 'ENABLE_CORS',
    NOSQL_CONNECTION_STRING = 'NOSQL_CONNECTION_STRING',
    JWT_KEY = 'JWT_KEY',
    JWT_EXPIRATION = 'JWT_EXPIRATION',
    TWILIO_ACCOUNT_SID = 'TWILIO_ACCOUNT_SID',
    TWILIO_AUTH_TOKEN = 'TWILIO_AUTH_TOKEN',
    TWILIO_VERIFICATION_SERVICE_SID = 'TWILIO_VERIFICATION_SERVICE_SID',
    SMS_API_URL = 'SMS_API_URL',
    SMS_API_TOKEN = 'SMS_API_TOKEN',
    HA_URL = 'HA_URL',
    HA_TOKEN = 'HA_TOKEN',
}